export const SET_PAYMENT_USER = "app/payment/SET_PAYMENT_USER";

export const DIALOG_SCREENS = {
  PAYMENT: "PAYMENT",
  REGISTER_CARD: "REGISTER_CARD",
  CARD_LIST: "CARD_LIST",
  RECEIPT: "RECEIPT"
};
